from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

import cv2
import numpy as np

from .config import MathematicalAnimeStyle


@dataclass(frozen=True)
class ToneFieldResult:
    """
    Complete mathematical fields generated by MTH-03.
    """

    output_rgb: np.ndarray

    input_rgb: np.ndarray

    luminance: np.ndarray

    local_luminance: np.ndarray

    local_detail: np.ndarray

    normalized_detail: np.ndarray

    quantized_luminance: np.ndarray

    shadow_mask: np.ndarray

    highlight_mask: np.ndarray

    target_luminance: np.ndarray


class MathematicalToneField:
    """
    MTH-03 Mathematical Luminance/Tone Field Engine.

    Converts the MTH-02 RGB color field into a controlled
    anime-oriented luminance structure.

    Every pixel is evaluated.

    Input:
        RGB uint8 [0,255]
        or floating RGB [0,1]

    Output:
        RGB uint8 [0,255]
    """

    def __init__(
        self,
        style: Optional[MathematicalAnimeStyle] = None,
    ) -> None:

        self.style = (
            style
            or MathematicalAnimeStyle.creator_anime()
        ).validated()

    # ============================================================
    # INPUT VALIDATION
    # ============================================================

    @staticmethod
    def _validate_frame(
        rgb: np.ndarray,
    ) -> None:

        if not isinstance(
            rgb,
            np.ndarray,
        ):
            raise TypeError(
                "Input frame must be a numpy.ndarray"
            )

        if rgb.ndim != 3:
            raise ValueError(
                "Input frame must have shape (H, W, 3)"
            )

        if rgb.shape[2] != 3:
            raise ValueError(
                "Input frame must contain 3 channels"
            )

        if (
            rgb.shape[0] <= 0
            or rgb.shape[1] <= 0
        ):
            raise ValueError(
                "Input frame cannot be empty"
            )

    # ============================================================
    # NORMALIZATION
    # ============================================================

    @staticmethod
    def _normalize(
        rgb: np.ndarray,
    ) -> np.ndarray:

        if rgb.dtype == np.uint8:

            return (
                rgb.astype(
                    np.float32
                )
                / 255.0
            )

        if np.issubdtype(
            rgb.dtype,
            np.floating,
        ):

            value = rgb.astype(
                np.float32,
                copy=False,
            )

            minimum = float(
                np.nanmin(value)
            )

            maximum = float(
                np.nanmax(value)
            )

            if (
                minimum >= 0.0
                and maximum <= 1.0
            ):
                return np.clip(
                    value,
                    0.0,
                    1.0,
                )

            return np.clip(
                value / 255.0,
                0.0,
                1.0,
            )

        raise TypeError(
            "Input must be uint8 or floating-point RGB"
        )

    # ============================================================
    # LUMINANCE
    # ============================================================

    @staticmethod
    def calculate_luminance(
        rgb: np.ndarray,
    ) -> np.ndarray:

        return (
            0.2126 * rgb[..., 0]
            + 0.7152 * rgb[..., 1]
            + 0.0722 * rgb[..., 2]
        )

    # ============================================================
    # LOCAL LUMINANCE
    # ============================================================

    def calculate_local_luminance(
        self,
        luminance: np.ndarray,
    ) -> np.ndarray:

        sigma = max(
            0.1,
            float(
                self.style.smooth_sigma
            ),
        )

        local = cv2.GaussianBlur(
            luminance.astype(
                np.float32
            ),
            ksize=(0, 0),
            sigmaX=sigma,
            sigmaY=sigma,
            borderType=cv2.BORDER_REFLECT,
        )

        return np.clip(
            local,
            0.0,
            1.0,
        )

    # ============================================================
    # LOCAL DETAIL
    # ============================================================

    @staticmethod
    def calculate_local_detail(
        luminance: np.ndarray,
        local_luminance: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray]:

        detail = (
            luminance
            - local_luminance
        )

        denominator = np.maximum(
            local_luminance,
            1e-4,
        )

        normalized = (
            detail
            / denominator
        )

        normalized = np.clip(
            normalized,
            -2.0,
            2.0,
        )

        return (
            detail,
            normalized,
        )

    # ============================================================
    # SOFT SIGMOID
    # ============================================================

    @staticmethod
    def sigmoid(
        value: np.ndarray,
    ) -> np.ndarray:

        value = np.clip(
            value,
            -60.0,
            60.0,
        )

        return (
            1.0
            / (
                1.0
                + np.exp(-value)
            )
        )

    # ============================================================
    # SHADOW FIELD
    # ============================================================

    def calculate_shadow_mask(
        self,
        luminance: np.ndarray,
    ) -> np.ndarray:

        threshold = float(
            self.style.shadow_threshold
        )

        softness = max(
            1e-4,
            float(
                self.style.shadow_softness
            ),
        )

        mask = self.sigmoid(
            (
                threshold
                - luminance
            )
            / softness
        )

        return np.clip(
            mask,
            0.0,
            1.0,
        )

    # ============================================================
    # HIGHLIGHT FIELD
    # ============================================================

    def calculate_highlight_mask(
        self,
        luminance: np.ndarray,
    ) -> np.ndarray:

        threshold = float(
            self.style.highlight_threshold
        )

        softness = max(
            1e-4,
            float(
                self.style.highlight_softness
            ),
        )

        mask = self.sigmoid(
            (
                luminance
                - threshold
            )
            / softness
        )

        return np.clip(
            mask,
            0.0,
            1.0,
        )

    # ============================================================
    # TONAL QUANTIZATION
    # ============================================================

    def quantize_luminance(
        self,
        luminance: np.ndarray,
    ) -> np.ndarray:

        levels = max(
            2,
            int(
                self.style.color_levels
            ),
        )

        scaled = (
            luminance
            * float(levels - 1)
        )

        quantized = (
            np.round(scaled)
            / float(levels - 1)
        )

        return np.clip(
            quantized,
            0.0,
            1.0,
        )

    # ============================================================
    # CONTRAST CURVE
    # ============================================================

    def apply_contrast_curve(
        self,
        luminance: np.ndarray,
    ) -> np.ndarray:

        contrast = float(
            self.style.contrast
        )

        centered = (
            luminance
            - 0.5
        )

        result = (
            centered
            * contrast
            + 0.5
        )

        return np.clip(
            result,
            0.0,
            1.0,
        )

    # ============================================================
    # TONE FIELD
    # ============================================================

    def build_target_luminance(
        self,
        luminance: np.ndarray,
        local_luminance: np.ndarray,
        normalized_detail: np.ndarray,
        quantized_luminance: np.ndarray,
        shadow_mask: np.ndarray,
        highlight_mask: np.ndarray,
    ) -> np.ndarray:

        tone_strength = float(
            self.style.tone_strength
        )

        detail_retention = float(
            self.style.detail_retention
        )

        shadow_strength = float(
            self.style.shadow_strength
        )

        highlight_strength = float(
            self.style.highlight_strength
        )

        # --------------------------------------------------------
        # Base tonal simplification
        # --------------------------------------------------------

        base = (
            luminance
            * (1.0 - tone_strength)
            + quantized_luminance
            * tone_strength
        )

        # --------------------------------------------------------
        # Reintroduce controlled local detail
        # --------------------------------------------------------

        detail_component = (
            normalized_detail
            * local_luminance
            * detail_retention
        )

        target = (
            base
            + detail_component
        )

        # --------------------------------------------------------
        # Shadow shaping
        # --------------------------------------------------------

        target = target * (
            1.0
            - shadow_mask
            * shadow_strength
        )

        # --------------------------------------------------------
        # Highlight shaping
        # --------------------------------------------------------

        target = target + (
            highlight_mask
            * highlight_strength
        )

        # --------------------------------------------------------
        # Keep the result between valid luminance limits
        # --------------------------------------------------------

        target = np.clip(
            target,
            0.0,
            1.0,
        )

        # --------------------------------------------------------
        # Global contrast
        # --------------------------------------------------------

        target = self.apply_contrast_curve(
            target
        )

        return np.clip(
            target,
            0.0,
            1.0,
        )

    # ============================================================
    # RGB RECONSTRUCTION
    # ============================================================

    @staticmethod
    def reconstruct_rgb(
        rgb: np.ndarray,
        source_luminance: np.ndarray,
        target_luminance: np.ndarray,
    ) -> np.ndarray:

        denominator = np.maximum(
            source_luminance,
            1e-4,
        )

        ratio = (
            target_luminance
            / denominator
        )

        ratio = np.clip(
            ratio,
            0.0,
            3.0,
        )

        result = (
            rgb
            * ratio[..., None]
        )

        return np.clip(
            result,
            0.0,
            1.0,
        )

    # ============================================================
    # MAIN TRANSFORMATION
    # ============================================================

    def transform(
        self,
        rgb: np.ndarray,
    ) -> ToneFieldResult:

        self._validate_frame(
            rgb
        )

        normalized = self._normalize(
            rgb
        )

        # --------------------------------------------------------
        # 1. Original luminance
        # --------------------------------------------------------

        luminance = (
            self.calculate_luminance(
                normalized
            )
        )

        # --------------------------------------------------------
        # 2. Local luminance field
        # --------------------------------------------------------

        local_luminance = (
            self.calculate_local_luminance(
                luminance
            )
        )

        # --------------------------------------------------------
        # 3. Local detail
        # --------------------------------------------------------

        (
            local_detail,
            normalized_detail,
        ) = self.calculate_local_detail(
            luminance,
            local_luminance,
        )

        # --------------------------------------------------------
        # 4. Tonal quantization
        # --------------------------------------------------------

        quantized = (
            self.quantize_luminance(
                luminance
            )
        )

        # --------------------------------------------------------
        # 5. Shadow field
        # --------------------------------------------------------

        shadow_mask = (
            self.calculate_shadow_mask(
                luminance
            )
        )

        # --------------------------------------------------------
        # 6. Highlight field
        # --------------------------------------------------------

        highlight_mask = (
            self.calculate_highlight_mask(
                luminance
            )
        )

        # --------------------------------------------------------
        # 7. Mathematical target tone
        # --------------------------------------------------------

        target = (
            self.build_target_luminance(
                luminance=luminance,
                local_luminance=local_luminance,
                normalized_detail=normalized_detail,
                quantized_luminance=quantized,
                shadow_mask=shadow_mask,
                highlight_mask=highlight_mask,
            )
        )

        # --------------------------------------------------------
        # 8. Reconstruct RGB
        # --------------------------------------------------------

        output = self.reconstruct_rgb(
            normalized,
            luminance,
            target,
        )

        # --------------------------------------------------------
        # 9. Convert to uint8
        # --------------------------------------------------------

        output_rgb = (
            output
            * 255.0
        ).round().astype(
            np.uint8
        )

        input_rgb = (
            normalized
            * 255.0
        ).round().astype(
            np.uint8
        )

        return ToneFieldResult(
            output_rgb=output_rgb,
            input_rgb=input_rgb,
            luminance=luminance,
            local_luminance=local_luminance,
            local_detail=local_detail,
            normalized_detail=normalized_detail,
            quantized_luminance=quantized,
            shadow_mask=shadow_mask,
            highlight_mask=highlight_mask,
            target_luminance=target,
        )

    # ============================================================
    # SIMPLE API
    # ============================================================

    def render(
        self,
        rgb: np.ndarray,
    ) -> np.ndarray:

        return self.transform(
            rgb
        ).output_rgb


def compute_tone_field(
    color_field: np.ndarray,
    style: Optional[MathematicalAnimeStyle] = None,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Compatibility function for pipeline compositor.
    Returns (Y_original, Y_anime, toned_color_field): All float32 in [0.0, 1.0].
    """
    engine = MathematicalToneField(style)
    res = engine.transform(color_field)
    return (
        res.luminance,
        res.target_luminance,
        res.output_rgb.astype(np.float32) / 255.0,
    )
